### PR TITLE
General updates and maintenance

### PR DESCRIPTION
**Pull request by kahwee**
I didn't change much except that I saw your test isn't passing. Added gitignore and updated npm packages.

### CODE REVIEW

**Comment by gmaclennan** [comment]
Fixed non-passing test in https://github.com/substack/bulk-require/commit/98c2133cf8df07cac2d08dfe5c560da9635468e3

**Comment by lpinca** [comment]
Ping. Can you update glob to version >= 5.0.15 ? This will silence the annoying warning about minimatch.

**Comment by Meekohi** [comment]
Agreed -- current version of `glob` is 7.0.6 and will get rid of deprecation notices.

**Comment by benjamine** [comment]
+1, as mentioned @lpinca this fixes a potential security vulnerability reported by NSP:
https://nodesecurity.io/advisories/118  (Regular Expression Denial of Service)

**Comment by kahwee** [comment]
Updated in a different pull request as my fork is lost. Closing this in favor of #11. Thanks @benjamine, @gmaclennan and @lpinca

**Pull request closed without merging**
